# Generated by Django 2.0.6 on 2018-06-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lunch',
            name='spent',
            field=models.FloatField(),
        ),
    ]
