# Generated by Django 2.0.6 on 2018-06-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20180625_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='realDate',
            field=models.DateField(auto_now=True, null=True, verbose_name='Day'),
        ),
    ]
