# Generated by Django 2.0.6 on 2018-06-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20180625_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lunch',
            name='day',
        ),
        migrations.AddField(
            model_name='day',
            name='day',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='day',
            name='spent',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='realDate',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.DeleteModel(
            name='Lunch',
        ),
    ]
