# Generated by Django 2.0.6 on 2018-06-26 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20180625_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Month'),
        ),
        migrations.AlterField(
            model_name='month',
            name='year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Year'),
        ),
    ]
