# Generated by Django 2.0.6 on 2018-06-28 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20180626_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='balance',
            field=models.FloatField(default=0.0),
        ),
    ]
